### ISSUE TITLE
Rubymine Broken Link Url Handler

### ISSUE THREAD

**Issue by Mackaber** [dejan/rails_panel#105]
The Rubymine url handler file is no longer available at this location 

http://devnet.jetbrains.com/servlet/JiveServlet/download/5477503-17455/RubyMine%20Url%20Handler.zip

Also, I'm not sure it this is compatible with current rubymine versions...

**Comment by modosc** [comment]
[this](https://github.com/charliesome/better_errors/wiki#opening-files-in-rubymine) suggests that a url like `x-mine://open?file=%{file}&line=%{line}` will work with rubymine - maybe they include this out of the box now? i don't have rubymine installed, can you test this locally?

**Comment by dgobaud** [comment]
Having this problem too

**Comment by Mackaber** [comment]
Confirmed working with 

RubyMine 2016.1
Build #RM-145.597, built on March 30, 2016
JRE: 1.8.0_40-release-b132 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o

without needing other gems 
(turns out I was forgetting to include the gem 'meta_request' XP)

**Comment by muescha** [comment]
but the current setting is not the right one:

https://github.com/dejan/rails_panel/blob/master/rails_panel/assets/javascripts/filters.js#L18

`rubymine://open?url=file://%s&line=%d`

here is `rubymine` but the doc at intellij suggest `x-mine`:

`x-mine://open?file=%{file}&line=%{line}`

**Comment by kreba** [comment]
@muescha We are setting the BetterErrors-Handler explicitly in our project to work around that:
```
if defined? BetterErrors
  BetterErrors.editor = case ENV['BETTER_ERRORS_EDITOR']
                        when 'rubymine' then 'x-mine://open?file=%{file}&line=%{line}'
                        else :sublime
                        end
end
```
HTH
