### ISSUE TITLE
Broken in Chrome 62

### ISSUE THREAD

**Issue by jakeNiemiec** [dejan/rails_panel#134]
(OSX)

![image](https://user-images.githubusercontent.com/16782063/32346431-5a9284aa-bfdb-11e7-86ca-70c7315dbdc5.png)
![image](https://user-images.githubusercontent.com/16782063/32347077-86ec49ee-bfdd-11e7-9954-260ffabcb7c6.png)

**Comment by taylorthurlow** [comment]
Same on Linux.

**Comment by awolfson** [comment]
Does #133 address this issue?

**Comment by jakeNiemiec** [comment]
@awolfson It seems like it.

**Comment by niborg** [comment]
Any word on #133 (or any other fix) being merged?

**Comment by jakeNiemiec** [comment]
cc @modosc

**Comment by modosc** [comment]
i can merge it now, @dejan can you roll up a release pls?

**Comment by mollat** [comment]
It's quite simple to hotfix it. Search for the panel.css file  (eg. find ~ -name panel.css). It should be somewhere like here:
~/.config/chromium/Default/Extensions/gjpfobpafnhjhbajcjgccbbdofdckggg/0.3.1_0/assets/stylesheets/panel.css

... and change line 295 to 'inline-block' like https://github.com/dejan/rails_panel/pull/133 shows.

**Comment by zurchpet** [comment]
@mollat sounds easy enough. Just that Chrome thinks the extension is broken and doesn't want to load it after the modofication. And when I tell Chrome to repai it ist just redownloads the extension with the flaw in the CSS.
Any way to tell Chrome to not check if anything has changed in this extension?

**Comment by tomrossi7** [comment]
I see that was merged, how can I install the update?

**Comment by dejan** [comment]
New version of extension (0.3.2) released, it should be available soon. Thanks @joshmfrankel for the fix and @modosc for taking care of it.
