### ISSUE TITLE
Long lists scroll off the screen

### ISSUE THREAD

**Issue by bbugh** [dejan/rails_panel#140]
Some of our report pages have a lot of partials (that cache). On the initial uncached page render, there are so many partials that the RailsPanel popup scrolls off the bottom of the screen, and we can't see it without `Cmd+-` to shrink the page size. Even then, some pages overflow off the bottom.

Our solution has been to set some css on `.profiler-popup` using the Stylebot Chrome extension, but I thought perhaps the panel could support this natively rather easily.

```
.profiler-popup {
  height: 100vh;
  overflow: scroll;
}
```

**Comment by dejan** [comment]
This should not happen anymore in the new version
