### ISSUE TITLE
Rails panel not displaying information on new chrome update

### ISSUE THREAD

**Issue by cenderin** [dejan/rails_panel#142]
I am unable to get rails panel working with the new chrome update, wondering if its something chrome changed and broke how it worked.  Anyone else have any issues with this?  

macOS 10.13.3
Chrome Version 65.0.3325.162 (Official Build) (64-bit)

Update:  Seems like it not receiving the page information when it loads.  Couple times it snuck through when using a pry binding.

**Comment by gencer** [comment]
I've updated today (usually get updates regularly but somehow it did not). However, I have the same problem. Panel is empty with latest version of Chrome.

**Comment by Mayurifag** [comment]
+1

**Comment by cenderin** [comment]
Still does not work for me.  I am using chrome canary and it is working tho.

**Comment by blaszczakphoto** [comment]
Still does not work on Version 71.0.3578.98 (Official Build) (64-bit) OSX
