### ISSUE TITLE
Update CircleCI config to 2.0

### ISSUE THREAD

**Issue by gogiel** [dejan/rails_panel#155]
CircleCI no longer executes tests.

> Service alert: Your project references CircleCI 1.0 or it has no configuration. CircleCI 1.0 and projects without configuration files are no longer supported. You must update your project to use CircleCI 2.0 configuration to continue. [Learn more](https://circleci.com/sunset1-0/).

**Comment by gogiel** [comment]
@dejan please update your keys on CircleCI: https://circleci.com/gh/dejan/rails_panel/59

**Comment by gogiel** [comment]
@dejan please also enable CI tests for PRs.

**Comment by dejan** [comment]
This is all done.
