### ISSUE TITLE
Use rspec instead of minitest

### ISSUE THREAD

**Issue by gogiel** [dejan/rails_panel#157]
[RSpec](http://rspec.info/) is much more feature rich compared to minitest. It makes testing much easier.

Task: rewrite meta_request unit tests

**Comment by dejan** [comment]
@gogiel did you had a chance to convert some tests? I'd like to switch to RSpec as well but don't want to double the effort. But if you haven't started on it, I'll do it now.

**Comment by gogiel** [comment]
No, haven't started it.
