### ISSUE TITLE
Update styling

### ISSUE THREAD

**Issue by gogiel** [dejan/rails_panel#159]
Update styling to match new Chrome/devtools flat design.

**Comment by jtmkrueger** [comment]
would respecting theme colors be a good addition to this issue? It'd be nice if there were at least light/dark themes, but if it used base theme colors that'd be even better

**Comment by dejan** [comment]
Style was updated in the new version. Unfortunatelly theme colors are not available in plugin code. Dark/Light preference is, but lets have another issue for that if needed and close this one.

![Screenshot from 2024-04-24 23-16-32](https://github.com/dejan/rails_panel/assets/4494/c2e2189b-7090-412e-953e-82cb2b58e378)
