### ISSUE TITLE
Stack Level too deep raised when performing a JSON Request

### ISSUE THREAD

**Issue by zuuno** [dejan/rails_panel#17]
Hello,

I have a little problem with meta_request, which is apparently raising a Stack Level Too Deep on ActionDispatch::Reloader at line 70.

It occurs when performing a JSON request with rest_client.

My Configuration:
Server : webrick or unicorn
Rails 3.2.8

Did someone here experienced the same error ?

Thank you

**Comment by anshulkatare** [comment]
The issue is coming again in version 0.3.4.
