### ISSUE TITLE
left bar cuts off my display in Mac/Chrome

### ISSUE THREAD

**Issue by whartonn** [dejan/rails_panel#24]
Thanks for your extension!! When the log runs more than one page a scrollbar appears and cuts off a bit of my "total" column (see attached). Perhaps it's due to my use of other extensions? I'm not sure. I'm using Mac OS 10.6.8 and chrome. I can't seem to get rid of it.

![Screen shot 2013-01-05 at 5 33 36 PM](https://f.cloud.github.com/assets/3431/45213/acd31d0e-5755-11e2-979d-ed3df732a8c7.png)

**Comment by dejan** [comment]
The UI was reimplemented from scratch so this is obosolete
