### ISSUE TITLE
[enhancement] Better params parsing?

### ISSUE THREAD

**Issue by schiza** [dejan/rails_panel#44]
It would be lovely, if params could be represented in a 'tree' way, for nested objects (hashes, arrays, etc.), that you can clearly read/collapse. For now, it's only a little bit help for reading params (especially when you are i.e. updating your model and sending nested hash of attributes).

**Comment by YushengLi** [comment]
+1 for this, this is the only reason I have to check development log after using rails_panel，a formatted params would be easy for debugging.

**Comment by dejan** [comment]
Thanks for suggestion! Implemented in https://github.com/dejan/rails_panel/pull/201
