### ISSUE TITLE
Subsequent clicks on file links don't open.

### ISSUE THREAD

**Issue by jdguzman** [dejan/rails_panel#71]
I am having a strange issue when I click on a file link the first one opens fine in my selected editor but subsequent clicks do nothing until the page is refreshed.  I've tested with both TextMate and Sublime Text and get the same results.  In the case of Sublime Text I am running the subl handler through xcode and can see the first click handled in the log but subsequent clicks don't even get to the handler.

**Comment by tobypinder** [comment]
I know this is completely outside your control, but for reference (when people google this) I'm still experiencing the same problem on Chrome stable 40.0.2214.111. Undocking the panel remains a valid workaround, and the first click still works successfully regardless.

**Comment by dejan** [comment]
This is fixed in new version of the RailsPanel
