### ISSUE TITLE
Does it work on Ruby 2.1?

### ISSUE THREAD

**Issue by davidhq** [dejan/rails_panel#73]
![screen shot 2014-03-20 at 12 54 46 am](https://f.cloud.github.com/assets/3899/2467599/270ed4bc-afc2-11e3-9be2-2032706c6dac.png)

Stopped working for me I think after upgrade to Ruby 2.1

Not sure if that is the reason - any ideas? 

thank you

**Comment by tirdadc** [comment]
Still no dice, and this is with both Pow and Passenger.

**Comment by davidhq** [comment]
You still haven't given up on this ;) ?
