### ISSUE TITLE
meta_request in combination with activerecord-postgis-adapter results in SystemStackError

### ISSUE THREAD

**Issue by sanderhahn** [dejan/rails_panel#77]
SystemStackError: stack level too deep
on Ruby 2.1.2/Rails 4.1.2
when updating geo enabled attributes

**Comment by virtualfunction** [comment]
Still having this issue here too.

**Comment by teohoch** [comment]
+1 Ruby 2.4 Rails 5.1

**Comment by MateoGreil** [comment]
I get a SegFault without trace, when I insert in my psql with `activerecord-postgis-adapter`a geometry object. But When I insert something else, it work.

**Comment by dejan** [comment]
Fixed in the meantime. Make sure you run most recent version of the gem.
