### ISSUE TITLE
Atom support?

### ISSUE THREAD

**Issue by rjrobinson** [dejan/rails_panel#82]
Any way to allow for atom as the default error?

**Comment by littlell** [comment]
I want to use atom as the default editor too, thanks.

**Comment by justCxx** [comment]
+1

**Comment by zenry** [comment]
I think it's very easy to add it, I'll take a stab at it when I have time.

Atom URL handler
https://github.com/WizardOfOgz/atom-handler

**Comment by zeke** [comment]
Would love to see this work for Atom, too!
