### ISSUE TITLE
What is Rails/Breakdown/Other?

### ISSUE THREAD

**Issue by burtondav** [dejan/rails_panel#91]
I have an app that the Other is huge.  What is it?

ActiveRecord	225 ms
Rendering	180 ms
Other	1,686 ms

**Comment by guiporto** [comment]
+1

**Comment by germanotm** [comment]
+1

**Comment by thephw** [comment]
Best I can tell:

ActiveRecord is the database calls within the controller action.

Rendering is anything that eventually uses the render clause.

Other is everything from the controller action starting to returning less the two above. No routing, but inclusive of all the controller logic and saturation of AR models.

**Comment by dejan** [comment]
`Other` is anything but the ActiveRecored or template rendering. It's not measured but calculated by deducting those two from the total time.
