### ISSUE TITLE
[Question] Rubymine Integration

### ISSUE THREAD

**Issue by teohoch** [dejan/rails_panel#93]
I would like to know how to integrate Rubymine with Rails Panel. The Configuration tells me to download a Rubymine URL Handler but I've been unable to figure how to use the downloaded file. I'm using Rubymine 7.x in a Ubuntu machine, don't know if linux is supported for this? Thanks for the help!

**Comment by mediatainment** [comment]
Have the same problem here. I don't know where to put the downloaded file. DoubleClick on the icon, simply shows the Icon for one second in the Dock. Then it closes without exception.

Using Rubymine 7

**Comment by mediatainment** [comment]
I found out, that downloading the Chrome extension and open the UrlHandler once, works. Simply click on the links in the chrome extension, pointing to your code, and rubymine opens that corresponding file. (I did not made changes on "command-line launcher") I hope this helps.

**Comment by dejan** [comment]
Newly released RailsPanel v0.3.1 includes the fix for the RubyMine integration.
