### ISSUE TITLE
another race condition in storage.rb

### ISSUE THREAD

**Issue by Tectract** [dejan/rails_panel#94]
seeing this a lot on my setup:

Errno::ENOENT - No such file or directory @ rb_sysopen - /home/username/myProjectFolder/tmp/data/meta_request/e03a01f8-1bf8-4c0b-ba89-0ac40c06cc95.json:
  meta_request (0.3.4) lib/meta_request/storage.rb:16:in `read'
  meta_request (0.3.4) lib/meta_request/middlewares/meta_request_handler.rb:20:in`events_json'
  meta_request (0.3.4) lib/meta_request/middlewares/meta_request_handler.rb:11:in `call'

seems a lot like this issue:
https://github.com/dejan/rails_panel/issues/38

**Comment by raykin** [comment]
@Tectract has same problem here in Rails5, do you get a workaround?

**Comment by raykin** [comment]
just find live reload caused it, disable live reload extension can fix it. However I didn't find where to set live reload option to exclude tmp dir

**Comment by CodyBrouwers** [comment]
I'm seeing the same problem, any ideas?

**Comment by modosc** [comment]
i think it's possibly caused by this line:

https://github.com/dejan/rails_panel/blob/master/meta_request/lib/meta_request/storage.rb#L12

if a single page load generates more than 10 requests you'll lose the meta info from those requests. maybe that should be configurable?

**Comment by durnin** [comment]
Increasing the number @modosc indicated definitely helps.
